### ISSUE TITLE
Storing DateTime object while generating JWT cause "Object of class stdClass could not be converted to int"

### ISSUE THREAD

**Issue by GabrieleMartini** [sitepoint-editors/basic-php-jwt-auth-example#1]
Storing DateTime object in `iat` and `nbf` while generating JWT, as done in [authenticate.php](https://github.com/sitepoint-editors/basic-php-jwt-auth-example/blob/main/public/authenticate.php):

```
$issuedAt   = new DateTimeImmutable();
$data = [
    'iat'  => $issuedAt,         // Issued at: time when the token was generated
    'iss'  => $serverName,       // Issuer
    'nbf'  => $issuedAt,         // Not before
    'exp'  => $expire,           // Expire
    'userName' => $username,     // User name
];
```

 cause:

> Object of class stdClass could not be converted to int

It should be converted to timestamp, as in the [Firebase example](https://github.com/firebase/php-jwt#example)

```
$payload = array(
    "iss" => "http://example.org",
    "aud" => "http://example.com",
    "iat" => 1356999524,
    "nbf" => 1357000000
);
```

See also https://github.com/firebase/php-jwt/issues/212#issue-330031805

**Comment by benbroadaway** [comment]
Yep, it should be like 
```php
    // Create the token as an array
    $data = [
        'iat'  => $issuedAt->getTimestamp(), // Issued at: time when the token was generated
        'jti'  => $tokenId,                  // Json Token Id: an unique identifier for the token
        'iss'  => $serverName,               // Issuer
        'nbf'  => $issuedAt->getTimestamp(), // Not before
        'exp'  => $expire,                   // Expire
        'data' => [                          // Data related to the signer user
            'userName' => $username,         // User name
        ]
    ];

```

**Comment by settermjd** [comment]
Thanks for spotting that and providing the fixes.

**Comment by jameshibbard** [comment]
Thank you for reporting the issue. I have updated the article in our system, but will leave the issue open until I see the changes reflected on the site.

**Edit**: changes are live and the demo code has been updated. Thanks again.
